# Usamos una imagen oficial de Python ligera
FROM python:3.13.3-slim
# Evita que Python escriba archivos .pyc y buffee la salida (logs en tiempo real)
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PIP_ROOT_USER_ACTION=ignore

# Directorio de trabajo
WORKDIR /app

# Copiamos requerimientos de AWS e instalamos
COPY requirements-aws.txt .
RUN pip install --no-cache-dir -r requirements-aws.txt

# Copiamos el código fuente
COPY . .

# AWS App Runner por defecto usa el puerto 8080
ENV PORT=8080

# Usamos uvicorn para lanzar la app de AWS
CMD exec uvicorn aws_whatsapp.main:app --host 0.0.0.0 --port ${PORT}
